MovieDetailproject/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name = 'movieapp'
urlpatterns = [

    path('', views.index, name="index"),
    path('movie/<int:movie_id>/', views.detail, name="detail"),
    path('add/', views.add_movie, name="add_movie"),
    path('update/<int:id>', views.update, name='update'),
    path('Delete/<int:id>', views.delete, name='delete'),
]

MovieDetailproject/movieproject/movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movieproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

MovieDetailproject/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to="photos")

def __str__(self):
    return self.name

MovieDetailproject/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . form import MovieForm
# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, "index.html", context)
def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})
def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, "add.html")
def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request,id):
    if request.method =='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

MovieDetailproject/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name"><br><br>
<!--    <input type="text" name="desc" placeholder="Description of the movie"><br><br>-->
    <textarea name="desc" cols="40" rows="5" placeholder="Description of the Movie"></textarea><br><br>
    <input type="text" name="year" placeholder="Enter Year of the movie"><br><br>
    <input type="file" name="img"><br><br>
    <input type="submit"><br><br>
</form>
{% endblock %}

MovieDetailproject/movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Data View</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    ONLINE MOVIE STORE
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

MovieDetailproject/movieproject/templates/delete.html
{% extends 'base.html'%}
{% block body %}
<form method="post">
    {% csrf_token %}
   <h2 style="text-align:center">Are you Want to Delete this Movie?
    <input type="submit">
    </h2>
</form>
{% endblock %}

MovieDetailproject/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="250" height="250">
        </div>
            <div class="col-md-6">
               <h3>{{movie.name}}</h3> <br>
               <h5>{{movie.desc}}</h5><br>
                <h5>{{movie.year}}</h5><br>
                <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
                <a class="btn btn-primary" href="{% url 'movieapp:index' %}">Prev</a>
            </div>
    </div>

</div>
{% endblock %}

MovieDetailproject/movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}    <!-- this form is a variable that stored MovieForms from view.py   -->
    <input type="submit">

</form>
{% endblock %}

MovieDetailproject/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
<!--        {{i.id}}-->
        <div class="col-md-3" data-width="100">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200px" height="200px">
                     <div class="card-body">
                         <h5 class="card-title">{{i.name}}</h5>
                         <p class="card-text">{{i.desc}}</p>
                         <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">{{i.name}}</a>
                     </div>
            </div>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}